[workspace]
authors = ["chaetognatha <mattis.knulst@med.lu.se>"]
channels = ["conda-forge"]
name = "lolstats"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
polars = ">=1.35.1,<2"
jupyter = ">=1.1.1,<2"
requests = ">=2.32.5,<3"
ipython = ">=9.6.0,<10"
alive-progress = ">=3.2.0,<4"
